### ISSUE TITLE
questions about usage

### ISSUE THREAD

**Issue by celalp** [hendriau/ProxECAT#1]
reading the manual for the proxecat function was not entirely clear. 

For allele counts are these the counts of rare alleles per gene? As in they can be different variants of the same type or are we comparing counts of rare alleles found in case to the counts of the same alleles found in control?

I guess this applies for all categories x1,x2,x3,x4 in the example 

Thanks

**Comment by hendriau** [comment]
Thanks for your question.  We are comparing the total count of rare alleles of a certain type in cases or controls.  So, for example, x1 is the total number of rare, functional alleles in cases in the gene of interest and x3 is the total number of rare, functional alleles in controls in the gene of interest.  The exact variants do not need to be the same, just the thresholds and definitions used to define the type of variant (e.g. functional, MAF < 0.1%).  Then, x2 and x4 are the total number of rare, proxy alleles in the gene of interest for cases and controls respectively.

**Comment by celalp** [comment]
Thanks, that makes sense.
